# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import detector_service_pb2 as detector__service__pb2


class DetectorServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.DetectImage = channel.unary_unary(
                '/detector.DetectorService/DetectImage',
                request_serializer=detector__service__pb2.RowMajorImageMessage.SerializeToString,
                response_deserializer=detector__service__pb2.DetectionsResponse.FromString,
                )


class DetectorServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def DetectImage(self, request, context):
        """Returns detections on an image.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DetectorServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'DetectImage': grpc.unary_unary_rpc_method_handler(
                    servicer.DetectImage,
                    request_deserializer=detector__service__pb2.RowMajorImageMessage.FromString,
                    response_serializer=detector__service__pb2.DetectionsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'detector.DetectorService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class DetectorService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def DetectImage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/detector.DetectorService/DetectImage',
            detector__service__pb2.RowMajorImageMessage.SerializeToString,
            detector__service__pb2.DetectionsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
