# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: detector_service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='detector_service.proto',
  package='detector',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x16\x64\x65tector_service.proto\x12\x08\x64\x65tector\"$\n\x14RowMajorImageMessage\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\"F\n\x0c\x44\x65tectionBox\x12\x0c\n\x04ymin\x18\x01 \x01(\x05\x12\x0c\n\x04xmin\x18\x02 \x01(\x05\x12\x0c\n\x04ymax\x18\x03 \x01(\x05\x12\x0c\n\x04xmax\x18\x04 \x01(\x05\"0\n\x19\x44\x65tectionClassDescription\x12\x13\n\x0b\x64\x65scription\x18\x01 \x01(\t\"\x9d\x01\n\x12\x44\x65tectionsResponse\x12\x16\n\x0enum_detections\x18\x01 \x01(\x05\x12/\n\x0f\x64\x65tection_boxes\x18\x02 \x03(\x0b\x32\x16.detector.DetectionBox\x12>\n\x11\x64\x65tection_classes\x18\x03 \x03(\x0b\x32#.detector.DetectionClassDescription2`\n\x0f\x44\x65tectorService\x12M\n\x0b\x44\x65tectImage\x12\x1e.detector.RowMajorImageMessage\x1a\x1c.detector.DetectionsResponse\"\x00\x62\x06proto3'
)




_ROWMAJORIMAGEMESSAGE = _descriptor.Descriptor(
  name='RowMajorImageMessage',
  full_name='detector.RowMajorImageMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='detector.RowMajorImageMessage.data', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=36,
  serialized_end=72,
)


_DETECTIONBOX = _descriptor.Descriptor(
  name='DetectionBox',
  full_name='detector.DetectionBox',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ymin', full_name='detector.DetectionBox.ymin', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='xmin', full_name='detector.DetectionBox.xmin', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ymax', full_name='detector.DetectionBox.ymax', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='xmax', full_name='detector.DetectionBox.xmax', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=74,
  serialized_end=144,
)


_DETECTIONCLASSDESCRIPTION = _descriptor.Descriptor(
  name='DetectionClassDescription',
  full_name='detector.DetectionClassDescription',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='description', full_name='detector.DetectionClassDescription.description', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=146,
  serialized_end=194,
)


_DETECTIONSRESPONSE = _descriptor.Descriptor(
  name='DetectionsResponse',
  full_name='detector.DetectionsResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='num_detections', full_name='detector.DetectionsResponse.num_detections', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='detection_boxes', full_name='detector.DetectionsResponse.detection_boxes', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='detection_classes', full_name='detector.DetectionsResponse.detection_classes', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=197,
  serialized_end=354,
)

_DETECTIONSRESPONSE.fields_by_name['detection_boxes'].message_type = _DETECTIONBOX
_DETECTIONSRESPONSE.fields_by_name['detection_classes'].message_type = _DETECTIONCLASSDESCRIPTION
DESCRIPTOR.message_types_by_name['RowMajorImageMessage'] = _ROWMAJORIMAGEMESSAGE
DESCRIPTOR.message_types_by_name['DetectionBox'] = _DETECTIONBOX
DESCRIPTOR.message_types_by_name['DetectionClassDescription'] = _DETECTIONCLASSDESCRIPTION
DESCRIPTOR.message_types_by_name['DetectionsResponse'] = _DETECTIONSRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RowMajorImageMessage = _reflection.GeneratedProtocolMessageType('RowMajorImageMessage', (_message.Message,), {
  'DESCRIPTOR' : _ROWMAJORIMAGEMESSAGE,
  '__module__' : 'detector_service_pb2'
  # @@protoc_insertion_point(class_scope:detector.RowMajorImageMessage)
  })
_sym_db.RegisterMessage(RowMajorImageMessage)

DetectionBox = _reflection.GeneratedProtocolMessageType('DetectionBox', (_message.Message,), {
  'DESCRIPTOR' : _DETECTIONBOX,
  '__module__' : 'detector_service_pb2'
  # @@protoc_insertion_point(class_scope:detector.DetectionBox)
  })
_sym_db.RegisterMessage(DetectionBox)

DetectionClassDescription = _reflection.GeneratedProtocolMessageType('DetectionClassDescription', (_message.Message,), {
  'DESCRIPTOR' : _DETECTIONCLASSDESCRIPTION,
  '__module__' : 'detector_service_pb2'
  # @@protoc_insertion_point(class_scope:detector.DetectionClassDescription)
  })
_sym_db.RegisterMessage(DetectionClassDescription)

DetectionsResponse = _reflection.GeneratedProtocolMessageType('DetectionsResponse', (_message.Message,), {
  'DESCRIPTOR' : _DETECTIONSRESPONSE,
  '__module__' : 'detector_service_pb2'
  # @@protoc_insertion_point(class_scope:detector.DetectionsResponse)
  })
_sym_db.RegisterMessage(DetectionsResponse)



_DETECTORSERVICE = _descriptor.ServiceDescriptor(
  name='DetectorService',
  full_name='detector.DetectorService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=356,
  serialized_end=452,
  methods=[
  _descriptor.MethodDescriptor(
    name='DetectImage',
    full_name='detector.DetectorService.DetectImage',
    index=0,
    containing_service=None,
    input_type=_ROWMAJORIMAGEMESSAGE,
    output_type=_DETECTIONSRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_DETECTORSERVICE)

DESCRIPTOR.services_by_name['DetectorService'] = _DETECTORSERVICE

# @@protoc_insertion_point(module_scope)
